# Generated by Django 5.0.8 on 2024-10-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tg_id", models.BigIntegerField(unique=True, verbose_name="TG ID")),
                (
                    "username",
                    models.CharField(
                        default="Anonymous", max_length=200, verbose_name="Username"
                    ),
                ),
                (
                    "register_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Register date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                        ],
                        default="active",
                        max_length=100,
                        verbose_name="Status",
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("data", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
    ]
