# Generated by Django 5.0.8 on 2024-10-15 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[
                    ("consultant", "Consultant"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                ],
                default="active",
                max_length=100,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="ClientAppeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appeal_id",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Request id"
                    ),
                ),
                (
                    "register_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Register date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("work", "Work"),
                            ("completed", "Completed"),
                        ],
                        default="processing",
                        max_length=100,
                        verbose_name="Status",
                    ),
                ),
                ("appeal", models.TextField(verbose_name="Appeal Text")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="control_db.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appeal",
                "verbose_name_plural": "Appeals",
            },
        ),
    ]
