# Generated by Django 5.0.8 on 2024-10-15 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_db", "0002_alter_client_status_clientappeal"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientappeal",
            name="consultant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultant_appeals",
                to="control_db.client",
                verbose_name="Executor",
            ),
        ),
        migrations.AlterField(
            model_name="clientappeal",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_appeals",
                to="control_db.client",
                verbose_name="Client",
            ),
        ),
    ]
