# Generated by Django 5.0.8 on 2024-10-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_db", "0003_clientappeal_consultant_alter_clientappeal_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientappeal",
            name="answer",
            field=models.TextField(blank=True, null=True, verbose_name="Appeal Answer"),
        ),
    ]
