# Generated by Django 5.0.8 on 2024-10-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("control_db", "0004_clientappeal_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="data",
        ),
        migrations.RemoveField(
            model_name="client",
            name="state",
        ),
    ]
