# Generated by Django 5.0.8 on 2024-10-17 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_db", "0005_remove_client_data_remove_client_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Клиент", "verbose_name_plural": "Клиенты"},
        ),
        migrations.AlterModelOptions(
            name="clientappeal",
            options={"verbose_name": "Обращение", "verbose_name_plural": "Обращения"},
        ),
        migrations.AlterField(
            model_name="client",
            name="register_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата регистрации"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[
                    ("consultant", "Консультант"),
                    ("active", "Активный"),
                    ("inactive", "Неактивный"),
                ],
                default="active",
                max_length=100,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="username",
            field=models.CharField(
                default="Anonymous", max_length=200, verbose_name="Имя пользователя"
            ),
        ),
        migrations.AlterField(
            model_name="clientappeal",
            name="answer",
            field=models.TextField(blank=True, null=True, verbose_name="Ответ"),
        ),
        migrations.AlterField(
            model_name="clientappeal",
            name="appeal",
            field=models.TextField(verbose_name="Текст вопроса"),
        ),
        migrations.AlterField(
            model_name="clientappeal",
            name="appeal_id",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Id Обращения"
            ),
        ),
        migrations.AlterField(
            model_name="clientappeal",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_appeals",
                to="control_db.client",
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="clientappeal",
            name="consultant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultant_appeals",
                to="control_db.client",
                verbose_name="Консультант",
            ),
        ),
        migrations.AlterField(
            model_name="clientappeal",
            name="register_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="clientappeal",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "В процессе"),
                    ("work", "В работе"),
                    ("completed", "Выполнено"),
                ],
                default="processing",
                max_length=100,
                verbose_name="Статус",
            ),
        ),
    ]
