# Generated by Django 5.0.8 on 2024-10-17 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_db", "0006_alter_client_options_alter_clientappeal_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "verbose_name": "Пользователя",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="clientappeal",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_appeals",
                to="control_db.client",
                verbose_name="Пользователь",
            ),
        ),
    ]
