# Generated by Django 5.0.8 on 2024-10-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_db", "0007_alter_client_options_alter_clientappeal_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
