# Generated by Django 5.0.8 on 2024-10-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneralSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consultant_id_first",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Consultant 1"
                    ),
                ),
                (
                    "consultant_id_second",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Consultant 2"
                    ),
                ),
            ],
            options={
                "verbose_name": "General settings",
                "verbose_name_plural": "General settings",
            },
        ),
    ]
