# Generated by Django 5.0.8 on 2024-10-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalsettings",
            name="consultant_id_first",
            field=models.CharField(
                default="", max_length=200, null=True, verbose_name="Consultant 1"
            ),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="consultant_id_second",
            field=models.CharField(
                default="", max_length=200, null=True, verbose_name="Consultant 2"
            ),
        ),
    ]
