# Generated by Django 5.0.8 on 2024-10-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0003_alter_generalsettings_consultant_id_first_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generalsettings",
            options={"verbose_name": "Основные", "verbose_name_plural": "Основные"},
        ),
    ]
