# Generated by Django 5.0.8 on 2024-10-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0004_alter_generalsettings_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalsettings",
            name="consultant_id_first",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                null=True,
                verbose_name="Первый консультант",
            ),
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="consultant_id_second",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                null=True,
                verbose_name="Второй консультант",
            ),
        ),
    ]
